### ISSUE TITLE
Missing Expansion Panel

### ISSUE THREAD

**Issue by karol-202** [cfnz/muirwik#17]
I've noticed that there is no binding for the [ExpansionPanel](https://material-ui.com/components/expansion-panels/) component (along with ExpansionPanelDetails, etc.) in muirwik.

I needed to use it, so i implemented it in my fork, however I'm not sure if I should create PR, because:
- I wrote the component according to newest, v4 API (I don't know how much has the API changed comparing to the version muirwik is using),
- I made all props variables for these components nullable because I think it's more secure (think of trying to get value of undefined prop:
`mExpansionPanel { attrs.expanded.doSomething() // Will fail }`,
using nullable props it won't compile) but it's inconsistent with rest of muirwik on the other side,
- I omitted TransitionComponent and TransitionProps props of ExpansionPanel because I wasn't sure how to implement TransitionComponent (as far as I remember, other components in muirwik don't have these props too, so I think it's not a big problem)

If you find that ok, I will be happy to create a PR.

**Comment by cfnz** [comment]
Hi, Yes, I would be happy to take a look at the code... might not incorporate it until the version 4 release, but will be good to get some ideas.

I am getting ready to do a release for v3.9.3 of Material Design, mainly some changes in the build process and to update the version of lodash used because of a security issue.

But then I will start looking at version 4 and might make some other breaking changes, so would be good to look at options (e.g. I will have a look at what you are talking about will nullable props) and also I am thinking of reducing the number of constructors, having one main constructor that takes most common options, but not having every single property in an alternative constructor as you can still go attrs.property = x afterwards... Why? Just finding the amount of information presented in the IDE when constructing some items a bit overwhelming... but it would be good to bounce those ideas around a bit first and see what other people think... it might break some code so again would be good to hear any opinions...

**Comment by karol-202** [comment]
Hi, so [here](https://github.com/karol-202/muirwik/tree/expansion-panel/muirwik-components/src/main/kotlin/com/ccfraser/muirwik/components/expansion) is the code of expansion panels. When you are ready to incorporate the changes, tell me, so I will rebase the expansion-panel branch and make a pull request.

Regarding to props nullability, I'm not 100% sure what is a proper solution, because problem I was writting about is part of bigger problem with nullability in Kotlin/JS. In Kotlin/JVM only way to create an object is to create new instance invoking the constructor and that effectively unables you to not assign value to non-null variable. And in Kotlin/JS nothing stops you from creating empty object using either jsObject {} or js("{}") and then casting to given class or interface. And as you know this is the way React creates props for new components. So choosing between nullable or non-null props is not a no-brainer. On the one hand making props nullable protect you from potential error when accessing undefined props, but on the other hand, checking for null every time when accessing prop is a little bit cumbersome if the prop is required. So my way is to make all the required props non-null in order not to be forced to check for null every time using prop in my component (there is still danger related to not passing prop to the component, but this can be resolved by forcing to pass them through arguments of creating method (
```
fun RBuilder.xxx(requiredProp: String) = child(XXX::class) {
    attrs.requiredProp = requiredProp
}
```
)) and to make all the optional props nullable.
Most of props in Material-UI are optional (maybe even all, I haven't checked it up), what is reflected in Typescript source files in MUI repo ([example](https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/Button/Button.d.ts)), so I think the best way is to make them nullable.

Regarding to slimming constructors down, IMHO Kotlin's default arguments makes having a lot of parameters in a constructor not a big issue. Maybe just moving the most common options to the top of the arguments list would be a solution? But I haven't thought of it too much yet.

**Comment by cfnz** [comment]
Hi, sounds good... I have started looking at version 4, mine didn't compile off the bat (latest jssprovider stuff), but have been through most issues now... Have bumped versions of most dependencies along and one good thing is the time from compiling to the UI refreshing is much faster, not sure if it is the improvements in Kotlin or webpack or what, but it is a big improvement. Still a bit more work to do, but will look at incorporating the expansion panel soon.

In terms of the null-ability thing, it is a bit tricky. I like the intent of what you are stating, and on the surface it sounds like the way to go, but I did a bit of testing...

Nulls and undefined are subtly different in javascript. In some parts of Material UI (can't remember where now), I was passing in nulls and it was not working properly, but not passing in anything did make it work properly, hence all the param?.let { attrib.param = it} around the place.

The problem with an attrib being nullable in Kotlin is that in javascript, Kotlin turns it to null when not assigned, rather than being undefined. This is different to the typescript definitions where the props are optional - which is missing or undefined rather than being null... You can see this in the following example:
```
interface SomeProps : RProps {
    var test1: Boolean?
    var test2: Boolean?
    var test3: Boolean?
    var test4: Boolean?

    var test5: Boolean
    var test6: Boolean
    var test7: Boolean
    var test8: Boolean
}
```
Later
```
    attrs.test1 = null
    attrs.test2 = undefined
//    attrs.test3 we will leave as undefined by not assigning anything...
    attrs.test4 = true

//    attrs.test5 = null            // Does not compile as expected
//    attrs.test6 = undefined       // Does not compile
//    attrs.test7 we will leave as undefined by not assigning anything...
    attrs.test8 = true

    println("Test1 is ${attrs.test1}")    \\ is null - as expected
    println("Test2 is ${attrs.test2}")    \\ is null - hmm
    println("Test3 is ${attrs.test3}")    \\ is null - hmm - could cause us some issues
    println("Test4 is ${attrs.test4}")    \\ true - no surprises there
    println("Test5 is ${attrs.test5}")    \\ is undefined
    println("Test6 is ${attrs.test6}")    \\ is undefined - same as test 5 so no surprises
    println("Test7 is ${attrs.test7}")    \\ is undefined - same as test 5 so no surprises
    println("Test8 is ${attrs.test8}")    \\ true - no surprises there
```
So at first it sounded like a good idea, and I actually went and changed a few components to nullable and everything seemed to work OK, but then I recalled the issue I had sending in a null as a prop somewhere, and so did these tests, and test number 2 and 3 are the ones that could cause some issues.

I also based my code of other examples, like the actual kotlin wrappers, eg. [this](https://github.com/JetBrains/kotlin-wrappers/blob/master/examples/src/main/kotlin/example/Quill.kt) where they don't seem to use nullable...

So... I like the idea, but I am not 100% sure if it is a goer... I guess you don't often go looking into sub properties of a prop, you would usually test equality of it but often not go much further, not for the props of Material UI anyway. If creating your own components it maybe OK, but handing off the props to another library, it depends on how they handle the props being null vs undefined, and as mentioned, I know one case (though don't know where it is :-)) that Material UI liked undefined rather than null.

Summary... that was a bit of a blurb! But I think you raised an important point worth discussion/investigation... I want the wrapper library to be as good as possible, so if changing all the props to nullable would make it better, I think it would be worth it (and it didn't take long to change the few I did before rethinking it)... but after rethinking it... maybe it is not worth it because of the behaviour of any prop being nullable means it can no longer be undefined - which will cause some issues in Material UI (somewhere).

Happy for more discussion though :-)

**Comment by cfnz** [comment]
Version 4 is out... quite a few breaking changes, but if you are still interested you can make a pull request... otherwise I am happy to pull the code out of your fork :-)

**Comment by karol-202** [comment]
Glad to hear that muirwik is now compatible with Material UI 4. I'm not using muirwik nor React in Kotlin now, but I will probably come back to my Kotlin React project in next month, so maybe I'll give some feedback then.

I've just created a pull request with expansion panel. My version was written when the version of Material UI was 4.1.3, but it seems that there were no changes to expansion panels, so should work with the most recent update.
