### ISSUE TITLE
support IR compiler

### ISSUE THREAD

**Issue by christian-draeger** [cfnz/muirwik#37]
It seems that the lib is not working with kotlinJS IR compiler. 
here an example: https://github.com/christian-draeger/fullstack-kotlin-mpp-with-bootiful-react/blob/ir-compiler/frontend/build.gradle.kts#L28

without using muirwik everything works as expected.

```
> Task :frontend:compileKotlinJs FAILED
e: /Users/christiandrager/github/fullstack-kotlin-mpp-with-bootiful-react/frontend/src/main/kotlin/components/ComponentWithMaterialUi.kt: (3, 8): Unresolved reference: com
e: /Users/christiandrager/github/fullstack-kotlin-mpp-with-bootiful-react/frontend/src/main/kotlin/components/ComponentWithMaterialUi.kt: (4, 8): Unresolved reference: com
e: /Users/christiandrager/github/fullstack-kotlin-mpp-with-bootiful-react/frontend/src/main/kotlin/components/ComponentWithMaterialUi.kt: (5, 8): Unresolved reference: com
e: /Users/christiandrager/github/fullstack-kotlin-mpp-with-bootiful-react/frontend/src/main/kotlin/components/ComponentWithMaterialUi.kt: (14, 9): Unresolved reference: mButton
e: /Users/christiandrager/github/fullstack-kotlin-mpp-with-bootiful-react/frontend/src/main/kotlin/components/ComponentWithMaterialUi.kt: (14, 58): Unresolved reference: MButtonVariant
e: /Users/christiandrager/github/fullstack-kotlin-mpp-with-bootiful-react/frontend/src/main/kotlin/components/ComponentWithMaterialUi.kt: (14, 92): Unresolved reference: MColor

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':frontend:compileKotlinJs'.
```

KotlinJS plugin also supports the compiling to both, IR compiler backend and default compiler backend.
see --> https://kotlinlang.org/docs/reference/js-ir-compiler.html#authoring-libraries-for-the-ir-compiler-with-backwards-compatibility

the IR compiler with Kotlin/JS, enables aggressive optimizations, such as generated code size (through dead code elimination), and JavaScript and TypeScript ecosystem interoperability, etc...
since the IR will be the default in the future anyway (as far as i know) it should make sense for muirwik to support it. 

if this could be released with kotlin react 16.13.1-pre.124-kotlin-1.4.10 this would be great
also having the kotlin-react wrapper as a provided dependency would make a lot of sense. thereby the would not be bound to a specific kotlin-react wrapper version anymore instead it would rely on dependencies that should be provided at runtime.

**Comment by cfnz** [comment]
The IR compiler is still in Alpha so since the code works with the current compiler I am thinking there is an issue with the Alpha compiler.

I have had a look at the issues a couple of times now, but have not been able to figure anything out... while the compiler is still in Alpha I don't think I will spend too much more time on it, it may turn out to be a trivially simple fix, but it may well be because of the Alpha compiler which goes a bit beyond my level of experience... when the IR compiler gets a bit further along (e.g. beta) and there are still issues with it, I might spend some more time on it.

Someone else a bit more JS experience than me might be better placed to figure it out.

In the mean time, because the current code (and the 1.4.10 version to be released soon) works with the current compiler, I will close this issue for now as it might go away with a more stable version of the new compiler.

**Comment by cfnz** [comment]
OK... I couldn't help it and looked into it a little more - seems it is a known issue when using the kotlin wrappers and how things used to work, looks like currently all props (etc) have to be defined as external... this might change in later versions of the compiler... (https://kotlinlang.slack.com/archives/C0B8L3U69/p1585318146030900)

To get around this all the props (etc) interfaces would have to be marked as external and all the components marked as @JsExternal and that _might_ help make it work...

But from the linked post:

> Of course, we know that this is far from ideal. The team is having a close look at these cases, and any other issues you might report, and will try their best to improve and polish the developer experience over time. Solutions currently being evaluated include compiler checks, IDE inspections, DCE adjustments, and more.

So things might change in the future... so I think it is still worthwhile keeping this issue closed as the IR compiler settles down a bit things might change.
