### ISSUE TITLE
Update to follow Kotlin react

### ISSUE THREAD

**Issue by smallshen** [cfnz/muirwik#73]
https://github.com/JetBrains/kotlin-wrappers/commit/b0926da89ed2d1d33c887649b340f40af2ef2a83

**Comment by arkivanov** [comment]
Muirwik code does not compile after upgrading Kotlin Wrappers to `pre.284`. Various errors like: 

```
Cannot access class 'react.RBuilder'. Check your module classpath for missing or conflicting dependencies
Cannot access class 'react.Props'. Check your module classpath for missing or conflicting dependencies
'fun RBuilder.mContainer(maxWidth: Breakpoint? = ..., fixed: Boolean = ..., disableGutters: Boolean = ..., component: String = ..., className: String? = ..., handler: StyledHandler<MContainerProps>? /* = (StyledElementBuilder<MContainerProps>.() -> Unit)? */ = ...): Unit' can't be called in this context by implicit receiver. Use the explicit one if necessary
```

Perhaps because of the recent [changes](https://github.com/JetBrains/kotlin-wrappers/blob/d0ef539948e49f297720fd5f8d1bb848ceb62c5d/CHANGELOG.md). Maybe this should be also fixed in scope of this task?

**Comment by cfnz** [comment]
Version 5 branch was released some time ago, but just now merged into Master and included support for the latest wrappers, but note it uses the legacy version of the wrappers. Also check out possible retirement note on Muirwik in the readme.
